### PR TITLE
Replace Microsoft.Azure.Cosmos.Table with Azure.Data.Tables

### LINKED ISSUE #75: WindowsAzure.Storage 9.3.3 depreciation
WindowsAzure.Storage package is deprecated. This library has been split into multiple parts and replaced.
Do you have plans to switch to the actual Azure packages ?

### PR DESCRIPTION
**Pull request by uveta**
Microsoft.Azure.Cosmos.Table is slowly getting obsolete, replaced with Azure.Data.Tables package

resolves #75

### CODE REVIEW

**Comment by Bertk** [comment]
@nblumhardt Could you please review this PR and create a new pre-release for it?

**Comment by nblumhardt** [comment]
Thanks for the ping, @Bertk.

@serilog/reviewers-azure-table-storage unfortunately none of us appear to have bandwidth to review/maintain this project. Per the plan in https://github.com/serilog/serilog/issues/1627 it's likely this one will end up in `serilog-archive`, and future releases will need to be made from a community fork. I'll push forward with that as soon as I have some time free (unless I hear otherwise from you :-) )

@Bertk and @uveta, it may be best to fork and publish a replacement package, at this point.

**Comment by ThomasPe** [comment]
@Bertk @uveta I'd be interested in helping reviving this project. I'm not a serilog expert, but let me know if you need a hand e.g. with cicd etc.

**Comment by pwelter34** [comment]
Can this get moved to serilog-contrib?  I'd be willing to be a maintainer?  Hoping to get this package revived.

**Comment by ThomasPe** [comment]
@pwelter34 If I understood correctly we would need to move this to a completely new organization. If you're interested I'd be happy to help maintaining this. Perhaps lets continue this discussion here: https://github.com/serilog/serilog-sinks-azuretablestorage/issues/83

**Review by pwelter34 — APPROVED** [review]

**Pull request merged**
